//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisplayCredits
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class loansEntities : DbContext
    {
        public loansEntities()
            : base("name=loansEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<branch> branches { get; set; }
        public virtual DbSet<client> clients { get; set; }
        public virtual DbSet<credit> credits { get; set; }
        public virtual DbSet<diary> diaries { get; set; }
        public virtual DbSet<parameter> parameters { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
