//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisplayCredits
{
    using System;
    using System.Collections.Generic;
    
    public partial class credit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public credit()
        {
            this.diaries = new HashSet<diary>();
        }
    
        public int contract_no { get; set; }
        public Nullable<int> client_no { get; set; }
        public Nullable<decimal> branch_code { get; set; }
        public Nullable<decimal> opening_amount { get; set; }
        public string currency { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> maturity_date { get; set; }
    
        public virtual branch branch { get; set; }
        public virtual client client { get; set; }
        public virtual parameter parameter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<diary> diaries { get; set; }
    }
}
