//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisplayCredits
{
    using System;
    using System.Collections.Generic;
    
    public partial class diary
    {
        public int id { get; set; }
        public Nullable<int> contract_no { get; set; }
        public Nullable<int> installment_sequence { get; set; }
        public string transaction_type { get; set; }
        public string status { get; set; }
        public Nullable<decimal> interest_rate { get; set; }
        public Nullable<decimal> interest_amount { get; set; }
        public Nullable<decimal> principal_amount { get; set; }
        public Nullable<decimal> remaining_principal_amount { get; set; }
        public Nullable<System.DateTime> installment_date { get; set; }
    
        public virtual credit credit { get; set; }
        public virtual parameter parameter { get; set; }
        public virtual parameter parameter1 { get; set; }
    }
}
